os:
  - osx
  - linux

language: node_js

node_js:
  - "6.2" # will actually use nightly here
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
  - "6.7"
  - "6.8"
  - "6.9"
  - "7.0"

matrix:
  allow_failures:
    - node_js: "6.3"
    - node_js: "6.4"
    - node_js: "6.5"
    - node_js: "6.6"
    - node_js: "6.7"

before_script:
  - npm i -g gulp
  - npm i -g node-nightly
  - node-nightly

script:
    - gulp build
    - npm test
    - gulp tslint
