os:
  - osx
  - linux

language: node_js

node_js:
  - "6.2" # will actually use nightly here
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
  - "6.7"

before_script:
  - npm i -g gulp
  - npm i -g node-nightly
  - node-nightly --upgrade

script:
    - gulp build
    - npm test
    - gulp tslint
