os:
  - osx
  - linux

language: node_js

node_js:
  - "6.2" # will actually use nightly here
  - "6.11"
  - "7.0"
  - "7.10.0"
  - "8.0.0"
  - "8.1.2"
  - "8.4.0"

matrix:
  allow_failures:
    - node_js: "6.2"

before_script:
  - npm i -g gulp
  - npm i -g node-nightly
  - node-nightly

script:
    - gulp build
    - npm test
    - gulp tslint